#en
map ctrl+c copy_to_clipboard
map ctrl+shift+c send_text all \x03
map ctrl+v paste_from_clipboard

#ru
map ctrl+с copy_to_clipboard
map ctrl+shift+с send_text all \x03
map ctrl+м paste_from_clipboard

confirm_os_window_close 0
