{ config, pkgs, host, ... }:

let
	# Вспомогательная функция для генерации чисел от 1 до n
	range = start: end: builtins.genList (n: start + n) (end - start + 1);
	mod10 = n: if n == 10 then 0 else n;
	
	# Список классов для workspace 9
	workspace9Classes = [
		"org.telegram.desktop"
		"com.ayugram.desktop"
		"discord-canary"
		"discord"
		"legcord"
	];
	
	# Список браузеров для workspace 2
	browserClasses = [
		"firefox"
		"vivaldi-stable"
	];
	
	# Список редакторов кода для workspace 3
	editorClasses = [
		"code-oss"
		"code"
		"Code"
	];
	
	# Цифры для workspace bindings
	workspaceNumbers = range 1 10;
	
	# Коды клавиш
	keyCodes = {
		Q = "code:24";
		W = "code:25";
		E = "code:26";
		R = "code:27";
		T = "code:28";
		P = "code:33";
		S = "code:39";
		F = "code:41";
		H = "code:43";
		J = "code:44";
		C = "code:54";
		V = "code:55";
		M = "code:58";
	};
	
	# Функция для создания переменных клавиш
	mkKeyVar = key: code: "$KEY_${key} = ${code}";
	
	# Преобразуем в формат для settings
	keyVars = builtins.listToAttrs (map (key: {
		name = "$KEY_${key}";
		value = keyCodes.${key};
	}) (builtins.attrNames keyCodes));
	
in {
	wayland.windowManager.hyprland = {
		enable = true;
		
		settings = {
			autogenerated = 0;

			source = "~/.config/hypr/colors.conf";
			
			################
			### МОНИТОРЫ ###
			################
			monitor = [
				"eDP-1,1920x1080@60.01,0x0,1"
				"HDMI-A-1,1920x1080@74.97,0x0,1,mirror,eDP-1"#
			];
			
			###################
			### МОИ ПРОГРАММЫ ###
			###################
			"$terminal" = "kitty";
			#"$fileManager" = "dolphin";
			"$menu" = "wofi --show drun --gtk-dark --style ~/.config/wofi/style.css";
			
			#################
			### АВТОЗАПУСК ###
			#################
			exec-once = [
				"clipse -listen &"
				"wl-clip-persist --clipboard regular &"
				"swww-daemon --no-cache &"
				"python3 ~/scripts/set_wallpapers/main.py --instant &"
				"~/projects/ard_indicator/pc_monitor/target/release/pc_monitor &"
				"hyprmodify & udiskie &"
				"swaync &"
				"legcord & env DESKTOPINTEGRATION=1 AyuGram -- &"
			] ++ 
			(
				if host == "hynix_" then
					[]
				else if host == "hypoxlaptop" then
					["GDK_BACKEND=wayland eww daemon && eww open workspaces_bar && eww open metrics_laptop_bar && eww open time_bar"]
				else
					["GDK_BACKEND=wayland eww daemon && eww open workspaces_bar && eww open metrics_pc_bar && eww open time_bar"]
			);
			
			#############################
			### ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ###
			#############################
			env = [
				"XCURSOR_SIZE,24"
				"HYPRCURSOR_SIZE,24"
			];
			
			###################
			### РАЗРЕШЕНИЯ ###
			###################
			permission = [
				"/usr/(bin|local/bin)/grim, screencopy, allow"
			];
			
			#####################
			### ВНЕШНИЙ ВИД ###
			#####################
			"$topGap" = if host != "hynix_" then "60" else "10";
			"$bottomGap" = "10";
			"$rightGap" = "10";
			"$leftGap" = "10";
			
			# Динамическое создание переменных для клавиш
			} // keyVars // {
			
			general = {
				gaps_in = 5;
				gaps_out = "$topGap,$rightGap,$bottomGap,$leftGap";
				border_size = 5;
				"col.active_border" = "$active_border_color_1 $active_border_color_2 45deg";
				"col.inactive_border" = "$inactive_border_color_1 $inactive_border_color_2 45deg";
				resize_on_border = false;
				allow_tearing = false;
				layout = "dwindle";
			};
			
			xwayland = {
				force_zero_scaling = true;
			};
			
			decoration = {
				rounding = 10;
				rounding_power = 2;
				active_opacity = 1.0;
				inactive_opacity = 0.75;
				
				shadow = {
					enabled = true;
					range = 4;
					render_power = 3;
					color = "rgba(1a1a1aee)";
				};
				
				blur = {
					enabled = true;
					size = 3;
					passes = 1;
					vibrancy = 0.1696;
				};
			};
			
			animations = {
				enabled = "yes, please :)";
				
				bezier = [
					"easeOutQuint, 0.23, 1, 0.32, 1"
					"easeInOutCubic, 0.65, 0.05, 0.36, 1"
					"linear, 0, 0, 1, 1"
					"almostLinear, 0.5, 0.5, 0.75, 1"
					"quick, 0.15, 0, 0.1, 1"
				];
				
				animation = [
					"global, 1, 10, default"
					"border, 1, 5.39, easeOutQuint"
					"windows, 1, 4.79, easeOutQuint"
					"windowsIn, 1, 4.1, easeOutQuint, popin 87%"
					"windowsOut, 1, 1.49, linear, popin 87%"
					"fadeIn, 1, 1.73, almostLinear"
					"fadeOut, 1, 1.46, almostLinear"
					"fade, 1, 3.03, quick"
					"layers, 1, 3.81, easeOutQuint"
					"layersIn, 1, 4, easeOutQuint, fade"
					"layersOut, 1, 1.5, linear, fade"
					"fadeLayersIn, 1, 1.79, almostLinear"
					"fadeLayersOut, 1, 1.39, almostLinear"
					"workspaces, 1, 1.94, almostLinear, fade"
					"workspacesIn, 1, 1.21, almostLinear, fade"
					"workspacesOut, 1, 1.94, almostLinear, fade"
					"zoomFactor, 1, 7, quick"
				];
			};
			
			dwindle = {
				pseudotile = true;
				preserve_split = true;
			};
			
			master = {
				new_status = "master";
			};
			
			misc = {
				force_default_wallpaper = -1;
				disable_hyprland_logo = true;
			};
			
			#############
			### ВВОД ###
			#############
			input = {
				kb_layout = "us,ru";
				kb_variant = "";
				kb_model = "";
				kb_options = "grp:win_space_toggle";
				kb_rules = "";
				numlock_by_default = true;
				follow_mouse = 1;
				sensitivity = 0;
				
				touchpad = {
					natural_scroll = true;
				};
			};
			
			gesture  = "3, horizontal, workspace";
			
			device = {
				name = "epic-mouse-v1";
				sensitivity = -0.3;
			};
			
			###################
			### ГОРЯЧИЕ КЛАВИШИ ###
			###################
			"$mainMod" = "SUPER";
			
			# Генерация bind для workspace переключений
			bind = 
				# Базовые бинды
				[
				"SUPER&SHIFT, $KEY_Q, exit,"
				"SUPER&SHIFT, Return, exec, $terminal"
				"SUPER&SHIFT, $KEY_C, exec, $terminal"
				"ALT_L, F4, killactive,"
				"$mainMod, $KEY_M, workspace, 1"
				"$mainMod, $KEY_E, exec, $fileManager"
				"$mainMod, $KEY_T, togglefloating,"
				"$mainMod, $KEY_F, fullscreen,"
				"$mainMod, $KEY_R, exec, $menu"
				"$mainMod, $KEY_P, pseudo,"
				"$mainMod, $KEY_J, togglesplit,"
				"$mainMod, left, movefocus, l"
				"$mainMod, right, movefocus, r"
				"$mainMod, up, movefocus, u"
				"$mainMod, down, movefocus, d"
				"$mainMod, $KEY_S, togglespecialworkspace, magic"
				"$mainMod SHIFT, $KEY_S, movetoworkspace, special:magic"
				"$mainMod, mouse_down, workspace, e+1"
				"$mainMod, mouse_up, workspace, e-1"
				"SUPER CTRL, left, workspace, -1"
				"SUPER CTRL, right, workspace, +1"
				"ALT_L, TAB, exec, echo \"prev_tag\" | socat - UNIX-CONNECT:/tmp/hyprmodify/hypr_read.sock"
				"$mainMod, $KEY_H, exec, echo \"hide_bar\" | socat - UNIX-CONNECT:/tmp/hyprmodify/hypr_read.sock"
				#",Print, exec, grim -g \"$(slurp -d)\" - | wl-copy"
				",Print, exec, screenland"
				"SUPER, $KEY_V, exec, $terminal --class clipse -e 'clipse'"
				"ALT_R, $KEY_C, exec, hyprpicker --autocopy"
				",Scroll_Lock, exec, hyprlock"
				",XF86AudioStop, exec, spotify"
				",XF86Search, exec, firefox"
				"ALT_R, $KEY_W, exec, ~/scripts/set_wallpapers/main.py"
				"SUPER SHIFT, X, exec, pkill Xwayland"

				#autoclicker
				"ALT_R, F6, exec, ~/.config/hypr/autoclicker.sh"
			]
			#++ map (i: "$mainMod, ${toString i}, exec, hyprctl dispatch workspace $(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')${toString i}") (pkgs.lib.range 0 9)
			#++ map (i: "$mainMod SHIFT, ${toString i}, exec, hyprctl dispatch movetoworkspace $(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')${toString i}") (pkgs.lib.range 0 9);
			#workspace = map (i: "${toString i}, monitor:eDP-1") (pkgs.lib.range 0 9) ++ map (i: "${toString i}, monitor:HDMI-A-1") (pkgs.lib.range 10 19);

			
			# Генерация workspace переключений (1-10)
			++ (map (n: "$mainMod, ${toString (mod10 n)}, workspace, ${toString n}") workspaceNumbers)
			# Генерация перемещений на workspace (1-10)
			++ (map (n: "$mainMod SHIFT, ${toString (mod10 n)}, movetoworkspace, ${toString n}") workspaceNumbers);
			
			bindel = [
				",XF86AudioRaiseVolume, exec, pactl set-sink-volume 0 +2%"
				",XF86AudioLowerVolume, exec, pactl set-sink-volume 0 -2%"
				",XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 2%+"
				",XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 2%-"
			];
			
			bindl = [
				",XF86AudioNext, exec, playerctl next"
				",XF86AudioPause, exec, playerctl play-pause"
				",XF86AudioPlay, exec, playerctl play-pause"
				",XF86AudioPrev, exec, playerctl previous"
			];
			
			bindm = [
				"$mainMod, mouse:272, movewindow"
				"$mainMod, mouse:273, resizewindow"
			];
			
			##############################
			### ОКНА И РАБОЧИЕ СТОЛЫ ###
			##############################
			#windowrulev2 = [
			#	"workspace silent current, class:.*"
			#];
			windowrule = ["workspace silent current, class:.*"]++[
				#"monitor HDMI-A-1, match:title screenland-HDMI-A-1"
				#"monitor DP-1, match:title screenland-DP-1"
				#"float on, match:class screenland"
				#"no_anim on, match:class screenland"
				#"float on, match:title Save As"

				"suppressevent maximize, class:.*"
				"nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
				"opacity 0.85, class:$terminal"
				"float,class:(clipse)"
				"size 622 652,class:(clipse)"
				"stayfocused, class:(clipse)"
			]
			# Генерация правил для workspace 2 (браузеры)
			++ (map (class: "workspace 2 silent,class:${class}") browserClasses)
			
			# Генерация правил для workspace 3 (редакторы)
			++ (map (class: "workspace 3 silent,class:${class}") editorClasses)
			
			# Генерация правил для workspace 8 (steam)
			++ [ "workspace 8 silent,class:steam" ]
			
			# Генерация правил для workspace 9 (мессенджеры)
			++ (map (class: "workspace 9 silent,class:${class}") workspace9Classes)
			++ [
				"float, class:^(com.ayugram.desktop)$, title:^(Media viewer)$"
				"fullscreen, class:^(com.ayugram.desktop)$, title:^(Media viewer)$"
			]
			++ [
				"fullscreen, class:^(Matplotlib)$"
			]

			
			# Генерация правил для workspace 10 (spotify)
			++ [ "workspace 10 silent,class:Spotify" ];
			
		};
	};
}